export const TIME_ZONES = [
  { label: "UTC−12:00 — Baker Island Time", value: "Etc/GMT+12" },
  { label: "UTC−11:00 — American Samoa", value: "Pacific/Pago_Pago" },
  { label: "UTC−10:00 — Hawaii", value: "Pacific/Honolulu" },
  { label: "UTC−09:00 — Alaska", value: "America/Anchorage" },
  {
    label: "UTC−08:00 — Pacific Time (US & Canada)",
    value: "America/Los_Angeles",
  },
  { label: "UTC−07:00 — Mountain Time (US & Canada)", value: "America/Denver" },
  { label: "UTC−06:00 — Central Time (US & Canada)", value: "America/Chicago" },
  {
    label: "UTC−05:00 — Eastern Time (US & Canada)",
    value: "America/New_York",
  },
  { label: "UTC−04:00 — Atlantic Time (Canada)", value: "America/Halifax" },
  {
    label: "UTC−03:00 — Buenos Aires",
    value: "America/Argentina/Buenos_Aires",
  },
  { label: "UTC−02:00 — Mid-Atlantic", value: "Etc/GMT+2" },
  { label: "UTC−01:00 — Azores", value: "Atlantic/Azores" },
  { label: "UTC±00:00 — GMT", value: "Etc/UTC" },
  { label: "UTC+01:00 — West Africa / Central Europe", value: "Africa/Lagos" },
  {
    label: "UTC+02:00 — South Africa / Eastern Europe",
    value: "Africa/Johannesburg",
  },
  { label: "UTC+03:00 — East Africa / Moscow", value: "Africa/Nairobi" },
  { label: "UTC+03:30 — Tehran", value: "Asia/Tehran" },
  { label: "UTC+04:00 — UAE / Baku", value: "Asia/Dubai" },
  { label: "UTC+04:30 — Kabul", value: "Asia/Kabul" },
  { label: "UTC+05:00 — Islamabad / Karachi", value: "Asia/Karachi" },
  { label: "UTC+05:30 — India / Sri Lanka", value: "Asia/Kolkata" },
  { label: "UTC+05:45 — Nepal", value: "Asia/Kathmandu" },
  { label: "UTC+06:00 — Bangladesh", value: "Asia/Dhaka" },
  { label: "UTC+06:30 — Myanmar", value: "Asia/Yangon" },
  { label: "UTC+07:00 — Bangkok / Jakarta", value: "Asia/Bangkok" },
  { label: "UTC+08:00 — Beijing / Singapore / Perth", value: "Asia/Shanghai" },
  { label: "UTC+09:00 — Tokyo / Seoul", value: "Asia/Tokyo" },
  { label: "UTC+09:30 — Darwin / Adelaide", value: "Australia/Adelaide" },
  { label: "UTC+10:00 — Sydney / Brisbane", value: "Australia/Sydney" },
  { label: "UTC+11:00 — Solomon Islands", value: "Pacific/Guadalcanal" },
  { label: "UTC+12:00 — New Zealand / Fiji", value: "Pacific/Auckland" },
  { label: "UTC+13:00 — Tonga / Phoenix Islands", value: "Pacific/Tongatapu" },
  { label: "UTC+14:00 — Line Islands", value: "Pacific/Kiritimati" },
];
