export * as AUTH_URLS from "./auth";
export * as REMINDER_URLS from "./reminder";
export * as KNOWLEDGE_BASE_URLS from "./knowledge-base";
export * as BOT_URLS from "./bot";
export * as ANALYTICS_URLS from "./analytics";
export * as MEETING_PROVIDER_URLS from "./calendar";
export * as APPOINTMENT_URLS from "./appointment";
export * as API_KEY_URLS from "./api-key";
export * as TEMPLATE_URLS from "./template";
